### ISSUE TITLE
Bug with game country and time to beat

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#101]
There's a problem with the `/time_to_beats` endpoint from [IGDB](https://api-docs.igdb.com/#time-to-beat). Sometimes it returns NaN, but sometimes it works well. 

There's also a problem with the way we show countries. Some games have an empty country value.

Take the game _Firewatch_ for example:
> ![image](https://user-images.githubusercontent.com/11547406/61176840-08e57680-a585-11e9-8d62-b41e60a9ed09.png)

**Comment by drsherlock** [comment]
I can pick this one.
Do you want to hide these fields in case of empty and NaN values?

**Comment by danielgrijalva** [comment]
@drsherlock yeah that's exactly what I was thinking!

**Comment by drsherlock** [comment]
Time to beat will not work until it is fixed by IGDB team. Hiding the field for now.
Also, do you want to show just one country if multiple countries are present?

**Comment by danielgrijalva** [comment]
I would like to show all the countries involved 😃
