### ISSUE TITLE
Bug: Creating account causes plaintext html to be displayed in many error bars.

### ISSUE THREAD

**Issue by BenNF** [danielgrijalva/overworld#104]
Creating an account on the newest commit on master results in the following error.

![image](https://user-images.githubusercontent.com/9667215/61219043-54149c00-a6e1-11e9-8ba4-9f081576051a.png)
![image](https://user-images.githubusercontent.com/9667215/61219066-61ca2180-a6e1-11e9-81f6-d0cac028eadc.png)

This continues for awhile and eventually stops.

Looks like somehow its reading out a index.html file into error bars.

Looks like the error is caused by a 404 on the /api/users/register endpoint.

Any ideas on the cause of this?

**Comment by BenNF** [comment]
The error was due to the fact that I didn't have by `.env`'s configured correctly. This bug appears to only be in how the error is displayed when the backend server cannot be contacted. It should display a single error with a 404 message.

**Comment by danielgrijalva** [comment]
The API returns an HTML view for some errors (404 not found errors, for example). Using a `timeout` value on axios calls in the front end might be a solution?

> ![image](https://user-images.githubusercontent.com/11547406/61228185-a0101280-a6da-11e9-8dcc-d308157b4dd5.png)

**Comment by danielgrijalva** [comment]
Fixed by #143
