### ISSUE TITLE
Change rating system to 5-star

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#106]
Having a 1-10 based system is... annoying, mainly because 10 stars are harder to read/count for a human, and they take too much space. My proposal is to migrate towards a 5 star system with half-stars

Unfortunately the Semantic UI rating component doesn't support half stars, but [this library](http://dreyescat.github.io/react-rating/) does.

**Comment by zoeyyandi** [comment]
hi @danielgrijalva, is this issue up for grabs?

**Comment by danielgrijalva** [comment]
hey @zoeyyandi I'm about to submit a PR that solves this issue! :sweat_smile: sorry, I should've mentioned I was going to grab it.

**Comment by danielgrijalva** [comment]
Resolved by #107
