### ISSUE TITLE
Improve Journal 

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#110]
The Journal feature has been working for a couple of weeks now. You can log a game and add it to your library of played games with a specific date to indicate the day when you _finished_ it, just like on Letterboxd when you watch a movie.

But due to the nature of video games, right now this feature falls behind. The way we consume this kind of entertainment is very different from movies: you can't just say "hey I finished this game" like you do with movies. 

In Overworld, users might wish to say "I started playing X game!" or "I've been playing X game for a while but now I'm done with it because it's not for me". Or what happens with online games like Fortnite or League of Legends? I play those games, and I'd like to indicate that on X day I played a couple of LoL matches.

My proposal is to add a dropdown in the logging modal and let the user decide the type of journal entry (finished, started, played, abandoned...). In the profile, we can use little icons to differentiate between the types of entries.

I will be working on this and see if it's feasible for Overworld.

**Comment by raufabr** [comment]
Maybe users can add their LoL user name and we could get their current profiles from a site like op.gg?
e.g. https://euw.op.gg/summoner/userName=therauf

**Comment by danielgrijalva** [comment]
@raufabr yeah, that's something we can add to the "connections" section in the settings! maybe also include PSN, Steam, Xbox and what not
