### ISSUE TITLE
Update documentation with frontend testing info

### ISSUE THREAD

**Issue by mikesmith** [danielgrijalva/overworld#114]
Add a frontend testing section to the documentation.

Include packages/dependencies used, how to run tests, and possibly adding coverage instructions (similar to backend testing section).

**Comment by mikesmith** [comment]
@danielgrijalva I've created a draft in gitbook. Let me know if you can see the proposed changes and if there is anything that should be added/changed/updated. Thanks!

**Comment by danielgrijalva** [comment]
@mikesmith looks good to me - just merged it! Gonna close this issue now, thanks!
