### ISSUE TITLE
Wrong developer in game title

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#117]
**Describe the bug**
The developer showing besides the game title (next to the game's release year) is wrong for the game Rocket League, and possibly for other games too.

**To Reproduce**
1. Search for "rocket league" or go directly to the game's page
2. See that it's showing "Panic Button Games" instead of "Psyonix". 

**Expected behavior**
It should show the game's main developer, Psyonix in this case.

**Screenshots**
![image](https://user-images.githubusercontent.com/11547406/61558116-0074bc00-aa1b-11e9-8cf6-7d94d7d02e04.png)

It even shows the correct developer on the details section :thinking:

**Comment by raufabr** [comment]
@danielgrijalva I can have a go at this.

**Comment by danielgrijalva** [comment]
Sure, go ahead! @raufabr

**Comment by danielgrijalva** [comment]
The game Firewatch also has this problem - it's showing the publisher name instead of the developer.
> ![image](https://user-images.githubusercontent.com/11547406/61569613-07acc180-aa3d-11e9-9c17-49e4411ee480.png)

**Comment by raufabr** [comment]
Just so that I understand the logic correctly, can a video game only have one publisher and multiple developers?
The API has
`publisher: true || false ` for each company mentioned.

**Comment by danielgrijalva** [comment]
The game details show as many publishers/developers the game has, but in the title, only the main developer must be shown, which is always the first (_I think_...)

**Comment by raufabr** [comment]
You want to show the publisher name right? If so, the game Firewatch is doing it correctly.

I've fixed the issue with rocket league, will create a PR once you confirm.
