### ISSUE TITLE
Show more game information

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#121]
We should show more information in a game's page. We already have the data thanks to IGDB, so here's a list of what I'd like to show:
* ~~Screenshots (`screenshots` field)~~
* Videos (`videos` field, show only the trailer if available)
* Similar games (`similar_games` field)
* DLCs/Expansions (`dlcs` and `expansions` field)
* Age ratings in the Details section (`age_ratings` field)
* ~~Ratings (using the `<Rating />` component introduced in #96)~~

**Comment by danielgrijalva** [comment]
I'm gonna pick up the Ratings feature.

**Comment by danielgrijalva** [comment]
Added ratings with #122 and screenshots with #124

**Comment by Amrithnath** [comment]
Hey, I would like to give this a shot @danielgrijalva

**Comment by danielgrijalva** [comment]
Sure @Amrithnath! which option are you picking up?

**Comment by Amrithnath** [comment]
I would like to do all of them but if I'm required to choose one I'm currently working on the age ratings part

**Comment by danielgrijalva** [comment]
@Amrithnath Alright then! let me know if you need any help.

**Comment by Amrithnath** [comment]
Hey @danielgrijalva was busy over the weekend, Ill have some updates for you today though. I was just wondering if you knew what the number returned by the age_ratings field in the games API meant. I couldn't figure out how to extract the age_ratings based on that number

**Comment by danielgrijalva** [comment]
@Amrithnath that number is actually the ID of an age rating, not the age rating itself. 

If you use `age_ratings` alone in the `fields.py` file, it returns only the ID. So, you need to set that field to: `age_ratings.category` and also `age_ratings.rating` (this dot syntax is called multi-querying). The category is either ESRB or PEGI and the rating is, well, the rating.

Once the API returns the full age ratings field, you would display it on the frontend with `game.age_ratings.category + game.age_ratings.rating`

* https://api-docs.igdb.com/#age-rating 
* https://api-docs.igdb.com/#multi-query

**Comment by Amrithnath** [comment]
Hey @danielgrijalva , Thanks for the info , I should have read the docs completely my bad. I have attached a screenshot of how the age ratings appear. Let me know if that's fine.
![screenshot](https://user-images.githubusercontent.com/13913707/62106857-f036c980-b2c3-11e9-858a-9e9ca51a7de0.jpg)

**Comment by danielgrijalva** [comment]
@Amrithnath looks great, congrats! just one little thing: can you make it so the PEGI rating displays numbers? e.g. `PEGI 16`

**Comment by Amrithnath** [comment]
Hey, I got the video(trailer only) to display as well. Currently it is an embed from Youtube. Should the similar games and the DLC and expansions field be a separate tab in the details section? Here is a screenshot of how it looks currently
![Video](https://user-images.githubusercontent.com/13913707/62204301-92c97800-b3aa-11e9-943d-986e80d2e5f8.jpg)

**Comment by danielgrijalva** [comment]
* For the trailer I was thinking of something like this:
    > ![image](https://user-images.githubusercontent.com/11547406/62230090-eec5d980-b375-11e9-9361-c609fd7be642.png)

    When clicked, it should open a modal with the embed _or_ open a new tab to YouTube. I'm not sure which option would be better, what do you think?

* Regarding the similar games and DLCs section, those should be below the screenshots, using the Header component from Semantic UI for the titles:
    ```jsx
    <Header className="white">Similar games</Header>
    ...
    <Header className="white">Expansions and DLCs</Header>
    ```
    Each game in the similar games and dlc sections should be displayed as a small `<Cover />` component, something like this:
    ```jsx
    {similar_games.map(g => {
        return <Cover imageId={g.cover_id} size="big" slug={g.slug} className="small-cover-wrapper" />
        })
    }
    ```
    I'd be happy to do a visual mock up if you need further assistance!

**Comment by Amrithnath** [comment]
Hey @danielgrijalva I think a modal would be the best option for the video. I'll try to implement it in that way.

**Comment by Amrithnath** [comment]
I got the video to display on the modal but i discovered a bug in my implementation and I'm unable to figure out how to fix it. Here is a screenshot

![Video bug 2](https://user-images.githubusercontent.com/13913707/62292455-130fdc00-b484-11e9-9310-5891c20e3099.jpg)
![Vidseo Bug](https://user-images.githubusercontent.com/13913707/62292456-130fdc00-b484-11e9-8e30-33e030018539.jpg)

Basically the same trailer shows up multiple times if there are mutiple trailers with the name trailer in their title.

Also for some reason my styles.css for the video component is not getting loaded as I wanted to make the padding 0.

this is the content of the Video_holder function.

`const Video_holder = ({game})=>{
    var ID = null
    game.videos.map(v=>{
        if(v.name.toLowerCase().includes('trailer')){
            ID=v.video_id
        }
    })
    if(ID!==null){
        return(<Embed id={ID} placeholder='../../../../../../public/earth.ico' brandedUI={false} source='youtube' active={true}></Embed>)
    }
    else{
        return(null)
    }`

**Comment by Amrithnath** [comment]
Hey @danielgrijalva was busy over the weekend, will have an update for you today

**Comment by danielgrijalva** [comment]
@Amrithnath no worries friend. Did you figure out the root for the multiple-trailers bug?

**Comment by Amrithnath** [comment]
Yea it was fixed in the latest commit, It was because I was using the map function to map all names that matched trailers to create an embed. But for each name that matched trailer I used the same video ID. Fixed in #131

**Comment by Amrithnath** [comment]
Hey @danielgrijalva I was implementing the similar games feature and I keep getting this error

`Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

below is the index.js of my similar_games component
![image](https://user-images.githubusercontent.com/13913707/62628018-28837b00-b948-11e9-974b-2ac11e0e69d3.png)

Here is the similar_games.js from the similar_games.component
![image](https://user-images.githubusercontent.com/13913707/62628144-5d8fcd80-b948-11e9-8262-7bcfb81aea30.png)

**Comment by danielgrijalva** [comment]
@Amrithnath shouldn't there be a `return` statement before `game.similar_games.map(...)`? (line 7in the index.js file)

**Comment by Amrithnath** [comment]
Whoops my bad, that issue is solved now. hey suddenly the game object is returning an empty object from the back end. I'm not sure if this is an issue with their API or something. Even the game.cover.image_id (which was working just a few seconds before is failing.)

![image](https://user-images.githubusercontent.com/13913707/62646641-60041e80-b96c-11e9-9196-1a6d2e3274f1.png)

I didn't change anything is the backend  and this was code that I did not work on. Although it was working a few seconds before.

**Comment by danielgrijalva** [comment]
@Amrithnath maybe you've exceeded the API limit? remember you can only make 10k requests per month (you can check that on the "Stats" section on https://api.igdb.com)

**Comment by Amrithnath** [comment]
Doesn't seem like it says I have used 5600 requests over the past month. I'll try cloning the project again, that should fix it. Another weird thing is that only the game API seems to be failing on my project because the landing page is displaying everything properly.

**Comment by Amrithnath** [comment]
hey, sorry no updates for you in a while @danielgrijalva , I had some major git issues in my local-system where all my latest changes made for the similar_games feature was lost. Just got the project working again  so will rebuild it and push it for review

**Comment by Amrithnath** [comment]
Hey I built out the similar games feature. But there is a bug currently which I'm unable to fix currently. The Cover Images for the similar games are displaying in a landscape(4:3 ratio??) orientation rather than portrait. Tried changing the image size in the src link for the image to no avail.

![image](https://user-images.githubusercontent.com/13913707/62794805-a7b4b280-baf2-11e9-8ff4-a50e34be50b0.png)

Apart from that the cover on hover shows the game name and also links to the game in a new tab on click
![image](https://user-images.githubusercontent.com/13913707/62794989-36c1ca80-baf3-11e9-9f4f-9e5db09581b8.png)

Here is a reference of the cover image as displayed in the game details cover.

![image](https://user-images.githubusercontent.com/13913707/62795057-6d97e080-baf3-11e9-9062-462307101496.png)

and here is how it is displayed in the similar games section

![image](https://user-images.githubusercontent.com/13913707/62795084-843e3780-baf3-11e9-919a-dbe5f5ea66cb.png)

**Comment by danielgrijalva** [comment]
@Amrithnath it appears you're using the wrong URL for the cover 😅 

In the Similar_game.js file (line 7):
```jsx
const src=`https://images.igdb.com/igdb/image/upload/t_screenshot_${size}/${imageID}.jpg`
```

Notice the `t_screenshot_${size}`... it should be `t_cover_${size}` so the IGDB API returns an image with the correct size for a cover. Here's the docs for that: https://api-docs.igdb.com/#images

**Comment by Amrithnath** [comment]
Hey I have done the DLCs and Expansions feature.Here is a screenshot of DLCs. I wasnt able to find a game that returned the Expansions field

![image](https://user-images.githubusercontent.com/13913707/62856774-6bac6800-bd13-11e9-95f6-f12889b07f43.png)
![image](https://user-images.githubusercontent.com/13913707/62856793-7c5cde00-bd13-11e9-8595-d98ca8857eb3.png)

**Comment by Amrithnath** [comment]
hey @danielgrijalva do you have any feedback on this?

**Comment by danielgrijalva** [comment]
Sorry, I've been busy the last couple of weeks. I'm gonna review everything on your PR and provide some feedback now!

**Comment by alcoelho** [comment]
Hey, I really liked the project and I want to help with this issue. I'm not sure if the original post is up to date, but can I get the similar_games feature?

**Comment by filipe-gomes** [comment]
@danielgrijalva let me know if anything else still needs done on this, I'd love to help.

**Comment by aabuderi** [comment]
Hey @danielgrijalva I'm also really into this project. If the "Age ratings in the details" part is still available, I'd love to pick it up.

**Comment by danielgrijalva** [comment]
@Amrithnath @alcoelho @filipe-gomes @aabuderi this is still open in case you want to contribute!

**Comment by elliotwood1** [comment]
@danielgrijalva do any of these still need picking up? I'd be keen to contribute! Maybe age ratings?

**Comment by danielgrijalva** [comment]
@elliotwood1 hey sorry for the absence. Seems that Amrithnath didn't submit any PR with their work... nor did any of the above contributors, so it's still open if you wanna give it a try! :D

**Comment by Amrithnath** [comment]
hey you can check out #131 it fixes all of the issues there. Let me know what I can do to make it merge-able.

**Comment by MohammedBajuaifer** [comment]
Hey, I would like to work on this, is it still open?

**Comment by winlaithandar** [comment]
Hello @danielgrijalva I am a student studying computer science. For the opensource development module, we are supposed to choose a project and make some enhancement on it. Can i use your project for my assignment? And i want to try on Similar games (similar_games field) for contributing.
