### ISSUE TITLE
Truncate game summary

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#123]
**Is your feature request related to a problem? Please describe.**
Sometimes, a game's summary is too long and it takes up a lot of screen space.

**Describe the solution you'd like**
The summary should be truncated to ~5 lines (?) and display a "Read more" link to display the rest of the text.

Perhaps this can be achieved with the library [react-truncate](https://github.com/One-com/react-truncate).

**Comment by ProfoundWanderer** [comment]
![truncate](https://user-images.githubusercontent.com/18703678/61983022-58d02e80-afc4-11e9-983c-cba9242ed1de.gif)
Something like this?

**Comment by danielgrijalva** [comment]
@ProfoundWanderer yes! like that 💯

**Comment by danielgrijalva** [comment]
Fulfilled with #125
