### ISSUE TITLE
Add Integration/End-to-end tests

### ISSUE THREAD

**Issue by theVernon124** [danielgrijalva/overworld#138]
Hello! This is an interesting project and I observed that unit tests are covered mostly for API and partly for the front-end. To increase overall functional test coverage, I'd like to contribute by writing end-to-end tests, mainly for the front-end for now. I'm thinking of using pytest + selenium; If this sounds good, kindly assign the issue to me and I'll get right to it. Thank you!

**Comment by danielgrijalva** [comment]
Hi @theVernon124, again sorry for the delay. I just merged the tests you provided, thanks! should I leave this issue open in case you or someone else wants to add more tests?

**Comment by theVernon124** [comment]
Hi @danielgrijalva , no problem, and thanks for merging! Sure, you can leave the issue open just in case.
