### ISSUE TITLE
Bug when rating a game without backdrop

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#158]
**Describe the bug**
When you rate a game (or interact with it in any way) it is saved to the database for caching its data (name, id, cover and backdrop images, etc) and avoid extra calls to IGDB. This particular bug happens when you rate a game that doesn’t have a backdrop image, because the code tries to access an `undefined` array.

**To Reproduce**
1. Search for a game that doesn’t have a backdrop (background image). Example: `Super Mario All-Stars + Super Mario World`
2. Go to the game’s page
3. Click on the stars to rate it

**Screenshots**
![image](https://user-images.githubusercontent.com/11547406/68533403-a78ca480-02e5-11ea-8902-cc63ca20e251.png)

**Comment by pathak-pratik** [comment]
Hi. I have fixed this issue. Please review @danielgrijalva

**Comment by PathakPratik** [comment]
Please close this issue, since it has been fixed. Thanks.
