### ISSUE TITLE
Sign up page

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#162]
**Is your feature request related to a problem? Please describe.**
Right now users can only sign up from the `Get Started` button located in the landing page. There’s no independant `/signup` page where users can directly create their account.

**Describe the solution you'd like**
Besides having that button in the landing page, it’d be good to have a separate sign up page with a form.

**Additional context**
> ![image](https://user-images.githubusercontent.com/11547406/68792737-36acfb80-0609-11ea-8494-2f9dfa3d9faa.png)

**Comment by nad0m** [comment]
Hi @danielgrijalva, I'm interested in working on this feature. Possibly #163 as well. Are there any UI or theme requirements? I checked letterboxd.com and they seemed to be doing their sign in/up modally as well so I can't really draw any inspiration from it. :)

**Comment by danielgrijalva** [comment]
@nad0m sure, I will assign this and #163 to you.

About the UI mockups… I was thinking of just putting the modals “in-line” in the `/login` and `/signup` pages (hopefully you understand what I mean by in-line 😅).

I would add a [`<Backdrop />`](https://overworld.gitbook.io/docs/v/documentation/frontend/common-components/backdrop) component as well just to pretty things up.

**Comment by danielgrijalva** [comment]
@nad0m any updates?

**Comment by PathakPratik** [comment]
I could help complete this if it's available! :smiley:

**Comment by danielgrijalva** [comment]
Go ahead @PathakPratik 👍

**Comment by PathakPratik** [comment]
![signuppage](https://user-images.githubusercontent.com/17859354/72501909-1c3c0c00-385e-11ea-98b7-2cfb87bcb6e6.png)

How does this look? Any suggestions?

**Comment by danielgrijalva** [comment]
@PathakPratik I like it! but I’m not sure about the backdrop… it makes the form look a bit off and misplaced 🤔

**Comment by PathakPratik** [comment]
Agreed. Even I thought so. That's why I was asking for an opinion.

**Comment by PathakPratik** [comment]
I have explored some alternative design options. Please help me decide what looks better. Or you could suggest something. Once we decide what skeleton we could go with, then will fine-tune further on it.

**Comment by PathakPratik** [comment]
![signup1](https://user-images.githubusercontent.com/17859354/72668526-e8bfd400-3a4d-11ea-8189-0ae86bc295dd.png)
![signup2](https://user-images.githubusercontent.com/17859354/72668530-f412ff80-3a4d-11ea-8045-79862b9c992d.png)
![signup3](https://user-images.githubusercontent.com/17859354/72668531-f7a68680-3a4d-11ea-84ee-9e5d9b3dc66e.png)
![signup4](https://user-images.githubusercontent.com/17859354/72668544-1147ce00-3a4e-11ea-83c4-86872040e112.png)

**Comment by danielgrijalva** [comment]
I _love_ the first one and the last! I would probably go with the last one though because it looks easier to responsify for mobile devices 🤔

**Comment by PathakPratik** [comment]
Turns out both the designs are mobile-friendly. Hence, incorporated the first one for the login page and the last one for the signup page.
