### ISSUE TITLE
Log in page

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#163]
Extremely similar to #162. 

Basically, create a `/login` page so users can log in from there instead of depending on the landing page or the nav bar.

**Comment by danielgrijalva** [comment]
[@nad0m](https://github.com/nad0m) has been assigned to this issue.

**Comment by tpic12** [comment]
Hey @danielgrijalva is this issue still available? I love the idea behind Overworld and would love to help. Also, are you thinking of something where if the user is not logged in they will be redirected to the login/signup page when trying to access a private route?

**Comment by danielgrijalva** [comment]
@tpic12 this issue was fulfilled by #187
