### ISSUE TITLE
Replace <a /> with <Link /> components

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#164]
Using `<a href=“…” />` for links _destroys_ the DOM and the app’s state. The `<Link />` components from any router (we use [react-router](https://github.com/ReactTraining/react-router) in Overworld) use HTML history and preserve the DOM and state. 

Currently, we are using anchors links in several parts of the codebase. My proposal is to replace/refactor that code and use [`<Link />`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md) instead.

A way to speed up this refactor is to use the search functionality in VS Code. Search for “`<a `“ (include the trailing space) and go ahead with the refactor! 🚀

**Comment by lenniezelk** [comment]
@danielgrijalva can i work on this?

**Comment by danielgrijalva** [comment]
sure @lenniezelk be my guest 😃

**Comment by danielgrijalva** [comment]
Fixed by #165
