### ISSUE TITLE
Annoying 1Password extension in the <GameSearch /> component

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#170]
### Context
The 1Password extension (and other password managers like LastPass) have the functionality to autofill your usernames/passwords, and they commonly sit on the side of inputs in case you want to configure something or pick a password manually. This is great and I have nothing against that.

### Bug
The problem is that this functionality is “leaking” into the `<GameSearch />` component used in the `<ChooseFavorites />` component (located at [`src/modules/settings/components/choose-favorites`](https://github.com/danielgrijalva/overworld/blob/master/frontend/src/modules/settings/components/choose-favorites/index.js)). Obviously this is unnecessary, annoying and intrusive because sometimes you can’t pick a game. See the images below.

> ![image](https://user-images.githubusercontent.com/11547406/69885576-159c0a00-129b-11ea-9946-9cfe1d98124e.png)
It’s suggesting to autofill my username here… doesn’t make sense.

> ![image](https://user-images.githubusercontent.com/11547406/69885591-264c8000-129b-11ea-9855-310155422535.png)
Now I can’t pick the first result because the extension is covering it 🤷‍♂️

### Expected behaviour
> ![image](https://user-images.githubusercontent.com/11547406/69885617-454b1200-129b-11ea-8f27-c082fd2e8e35.png)

> ![image](https://user-images.githubusercontent.com/11547406/69885630-54ca5b00-129b-11ea-9714-8e5be7b953b2.png)

The input here should work like it isn’t related to any authentication functionality.

### Possible solutions
First of, we can’t tweak any 1Password code. However, the `<GameSearch />` component uses the [`<Search />`](https://react.semantic-ui.com/modules/search/) module from Semantic UI. Maybe there are some props we can pass it (or remove) to fix this bug. 

Also, head over to the [semantic-ui-react](https://github.com/Semantic-Org/Semantic-UI-React/issues) issues, maybe there’s something related in there.

I’m also open to refactoring this and create our own Search component.

**Comment by tlaudahl** [comment]
Can I take this? I downloaded 1password just to test this and I was able to get it to work without 1password showing up. 

Something I noticed while messing with it is if there are too many results they get cut off and there is no way to scroll or view the results past where its cut off which I could include the fix in my PR or you can create a new issue to address just that

**Comment by danielgrijalva** [comment]
Fixed by #180
