### ISSUE TITLE
Developer info and all games created by a particular developer

### ISSUE THREAD

**Issue by PathakPratik** [danielgrijalva/overworld#188]
Currently, on the game page, we show the developer of the game as a link which redirects to the homepage. Ideally, this to take us to the page where all the information of the developer including the games developed by him should be shown.

This is similar to the 'director' page in Letterboxd.

**Comment by PathakPratik** [comment]
@danielgrijalva I am working on this feature now.

**Comment by danielgrijalva** [comment]
PR #190 fulfills this request
