### ISSUE TITLE
Discover section with recommended video games

### ISSUE THREAD

**Issue by skekre98** [danielgrijalva/overworld#194]
I was hoping there was a way for users to discover video games in a personalized way. I was thinking we could recommend video games based on liked/played video games. We could accomplish this by leveraging the IGDB API and search for games based on liked games and sort games based on specific priority. I personally believe some good features to sort on would at first be genre and platform(this can be enhanced later). In terms of front end, there would be a discover section either in the user's profile or on the home page which would make a call to the API in the backend and render games that are returned and sorted.

**Comment by skekre98** [comment]
@danielgrijalva I can look into this feature.

**Comment by danielgrijalva** [comment]
@skekre98 hi, sorry for my absence. Any updates on this feature?
