### ISSUE TITLE
Prompting message when confirm a different password

### ISSUE THREAD

**Issue by elfjingjing** [danielgrijalva/overworld#196]
### Is your feature request related to a problem? Please describe.
Right now, the requirement for the password  is just "at least 8 characters".  I tried different combinations of numbers/characters/symbols, they all work. But when user types a different password for confirming step, there is no message to tell user that he/she typed a different password, only the "Sign up" button can't be clicked. 

So if the user typed different passwords by mistake, it would be very hard to  know why he/she cannot click the sign up button. 
<img width="408" alt="Screen Shot 2020-06-09 at 4 51 31 PM" src="https://user-images.githubusercontent.com/59683778/84212263-34613180-aa72-11ea-9336-0509520e5c6b.png">
* In this case, I typed "11111111", and then "11111112".

### Describe the solution you'd like
I would recommend to add a message like" password must match" to tell the user that he/she can't sign up due to the wrong password he/she provide during the confirm step.

### **Additional context**
For security reason, maybe we could make our requirements a little more complicated, like must include uppercase letters, or must be the combination of letters and numbers.

**Comment by dotis90** [comment]
I recently came across this project and I'm very interested in contributing. This is an issue I will be able to solve, so I'll start working on it.

**Comment by danielgrijalva** [comment]
@dotis90 go ahead, submit a PR when it's ready so I can review it :)

**Comment by farce1** [comment]
@dotis90 any update on this issue, are you still on it?

**Comment by jawad-nafad** [comment]
Is this issue solved by any chance? I want to have a look if not. TIA

**Comment by jawad-nafad** [comment]
@danielgrijalva thank you! I will have a look

**Comment by WilliamCheng12345** [comment]
Hi, I am interested in solving this issue. Has the issue been resolved? Thank you!

**Comment by jawad-nafad** [comment]
Hi William,
Daniel previously mentioned me that it is still open and I can continue on
solving, but unfortunately I got busy with my regular life so I could not
manage time to solve the issue. Therefore, I believe it is still open and
you can work on it. Cheers!

**Comment by WilliamCheng12345** [comment]
Oh ok, I will take a look.
