### ISSUE TITLE
Local setup issue

### ISSUE THREAD

**Issue by arunaaabh95** [danielgrijalva/overworld#198]
I have setup the project on my local machine after going through the setup guide. I have the following specification
 python 3.8
node 12.3 (>10 was recomended)
PostgreSQL 12

I do not get any issues with semantic ui during setup as mentioned in the doc but on running the project locally I could see the following issue
Client issue
![image](https://user-images.githubusercontent.com/15111263/85205059-437b9580-b336-11ea-9995-764ed586e2ac.png)

On Investigating the requests in backend I see this response:
Server response
![image](https://user-images.githubusercontent.com/15111263/85205040-28108a80-b336-11ea-9af6-a457c541bef5.png)

**Comment by danielgrijalva** [comment]
Hello! sorry for my absence. I ran into this issue too and got it solved by logging into [IGDB](https://api.igdb.com/) and generating a new API key, then paste it in the `.env` file located in the project root. This way I could make requests through Overworld again.

Let me know if this solves the issue.

**Comment by arunaaabh95** [comment]
Hey @danielgrijalva, I created and added the keys just like your said and it worked. I think it would be great idea if we include this in setup docs and then close the issue.

Thanks for the help.
