### ISSUE TITLE
Something Went Wrong Error

### ISSUE THREAD

**Issue by hawkens23** [danielgrijalva/overworld#207]
Every time I go to the website, it brings up a “Something Went Wrong” error, resulting in no functionality of the website. Both on IOS iPhone 6s and Windows PC.

**Comment by GekoShell** [comment]
I'm also receiving this error. Looking into the debug menu I found this, which could be the source.
![image](https://user-images.githubusercontent.com/65116471/115446249-d1523680-a20e-11eb-8650-65468044001a.png)
Some sort of error with the API? This may need to be looked into further.

**Comment by danielgrijalva** [comment]
@hawkens23 @GekoShell hey guys sorry for the late response. That error occurs when the API key expires. It's something that happens since Twitch bought IGDB, and now we are required to use Twitch authentication/dev console system: https://dev.twitch.tv/docs/authentication
