### ISSUE TITLE
Updated/Added files after following documentation initial setup steps

### ISSUE THREAD

**Issue by mikesmith** [danielgrijalva/overworld#53]
Hello! This is my first issue on GitHub, so please let me know if this isn't an issue or there is a better way to report this. If you think that this is more an artifact of my local config, please let me know. Thanks!

I followed the installation steps in the [setup](https://overworld.gitbook.io/docs/v/documentation/getting-started/setup) section of the documentation. Everything seems to work; however, I noticed a few things immediately after completing setup:

1. package.json and package-lock.json were updated. I wouldn't expect these to be updated after doing a first clean install. I did some research and it looks like ```npm install``` could overwrite these files. I found these references: [SO](https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json?rq=1), [```npm install```](https://docs.npmjs.com/cli/install), [```npm ci```](https://docs.npmjs.com/cli/ci.html). I reran the installation steps with ```npm ci``` and it looks like the files were not updated. Do you think the ```npm install``` step should be updated to ```npm ci``` for initial setup?

2. After running ```npm install```, Semantic UI asked a few questions via console. I chose all the defaults. I am not sure if the defaults were the correct answers to choose. Do you think think these should be added to the documentation for initial setup?

3. After installing Semantic UI, it added a new folder ```semantic/``` and a new file ```semantic.json```. Should these be in the .gitignore? Or should they be version controlled? Here is a relevant [SO post](https://stackoverflow.com/questions/32538811/semantic-ui-in-gitignore). 

If anything needs to be updated, I don't mind putting a PR together.

**Comment by danielgrijalva** [comment]
Hi @mikesmith! Thanks for pointing this out. And don't worry, it's perfectly fine to report this in an issue, that's what they're for!

1. I did a clean install and you're right, `npm install` modifies the package-lock. I then tried `npm ci` and it works fine, but I'm a little concerned about this, do you think it could break the app? :thinking: 
    
    >  It can be significantly faster than a regular npm install by **skipping certain user-oriented features**.

2. Yes, I forgot to add the Semantic UI setup in the docs, whoops :sweat_smile: I just used the default configuration (`Automatic`, then `Yes`, and finally use the `semantic/` folder).  
3. I think these Semantic files should be ignored _for now_ because we are not building/customizing our own theme yet, so you should include them in the `.gitignore`.  
  
If you want to update the docs go ahead! just remember to push to the `documentation` branch :+1:

**Comment by mikesmith** [comment]
Thanks @danielgrijalva!

1. 🤔That is a concern. I couldn't find any more explicit information about what "certain user-oriented features" are being skipped. If ```npm ci``` is meant for testing and CI, I would hope that it doesn't break the app. Another [SO](https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci) that I found might give a little more context around the differences.

2. I'll go ahead and start making some updates to the docs regarding Semantic installation.

3. I can update the ```frontend/.gitignore``` as well.

**Comment by danielgrijalva** [comment]
The project I installed with `npm ci` works as expected, it's not broken _yet_. Also, check this:  
  
> Use npm ci if you need a deterministic, repeatable build. For example during continuous integration, automated jobs, etc. and **when installing dependencies for the first time**, instead of npm install.

I think `npm ci` is the way to go, since what we want to achieve with the Setup section of the documentation is to do an installation for the first time :smile:

Thanks @mikesmith!

**Comment by danielgrijalva** [comment]
Resolved by #58 and #59
