### ISSUE TITLE
Mock requests to IGDB API 

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#57]
As pointed out in #56, I had to _temporarily_ remove tests for the `games` app as they are hitting the real API and wasting resources/requests. 

We should mock the IGDB API to re-integrate these tests. Here's a tutorial: https://realpython.com/testing-third-party-apis-with-mocks/

**Comment by mikesmith** [comment]
@danielgrijalva, I'm interested in taking this on if you don't mind.

**Comment by danielgrijalva** [comment]
@mikesmith go ahead!

**Comment by mikesmith** [comment]
In addition to https://realpython.com/testing-third-party-apis-with-mocks/, I used this article to figure out the mocking: http://engineroom.trackmaven.com/blog/real-life-mocking/

**Comment by danielgrijalva** [comment]
Fixed by #66
