### ISSUE TITLE
User ratings

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#62]
A bar graph that aggregates all the user ratings, like this:
![image](https://user-images.githubusercontent.com/11547406/60041405-27d0a700-9670-11e9-879c-d17a730007b5.png)

This component should appear in the sidebar (right) of the profile.

**Comment by BenNF** [comment]
Is this the ratings on the users profile? Or is this ratings on a game like Letterboxd does for films?

![image](https://user-images.githubusercontent.com/9667215/61069287-ef53fb80-a3d9-11e9-9793-1032ef1b723e.png)

**Comment by danielgrijalva** [comment]
This is for the users profile, but the component should be reusable so we can use it for game ratings in a game's page

**Comment by BenNF** [comment]
Ok sounds good, I've started work on this. 

Does the API already support getting all ratings by user or by game?  Or is that something that also needs to be added?

**Comment by danielgrijalva** [comment]
Nope not yet, this feature also involves adding the API logic.

Something like this can be done with the `Ratings` model:
```python
from actions.models import 
Ratings.objects.filter(user=1).values('rating')

>>> <QuerySet [{'rating': 7}, {'rating': 9}]>
```

**Comment by danielgrijalva** [comment]
And for the bar graph maybe [D3.js](https://d3js.org/)? or maybe something simpler? :thinking:

**Comment by BenNF** [comment]
I don't think this graph is complicated enough to need d3.js. I was able to build a decent looking version with some styling and divs.

**Comment by BenNF** [comment]
I've been trying to extend the profile endpoint to include include ratings but i'm not sure i'm fully understanding the architecture of the API. 
I added a `ratings` field to the Profile Serializer as well as adding 
`ratings = models.ManyToManyField(Ratings, related_name='ratings')`
to the custom user model but am running into some errors related to DB field names.

Is this the correct approach to extending the api? I may be misunderstanding how the DB is structured.

**Comment by danielgrijalva** [comment]
Hey @BenNF do you still need help with this? I see you pulled it off with your PR...
