### ISSUE TITLE
popular endpoint resolves to get-game view instead of get-popular

### ISSUE THREAD

**Issue by mikesmith** [danielgrijalva/overworld#65]
**Describe the bug**
`popular/` resolves to `get-game` instead of `get-popular` view. I think this may be due to the recent change of using a slug instead of a GUID for `get-game`.

`popular/` matches `<str:slug>/` first in the urlpatterns in `games/urls.py`. [Django Resource](https://docs.djangoproject.com/en/2.2/topics/http/urls/)

**Screenshots**
A screenshot of the popular games section on the landing page:

<img width="1007" alt="Screen Shot 2019-06-25 at 10 10 51 PM" src="https://user-images.githubusercontent.com/46382795/60153613-a7a66080-9799-11e9-9dee-e4da99633fac.png">

**Comment by mikesmith** [comment]
If the solution to this is as simple as re-ordering `popular/` to be before `<str:slug>/` in urlpatterns, I can throw this into my PR (#66).

**Comment by danielgrijalva** [comment]
@mikesmith yeah I think that's a possible solution. Can you see if it works? :open_mouth:

**Comment by mikesmith** [comment]
@danielgrijalva Yea! Will try and add it to the PR if it works.

**Comment by danielgrijalva** [comment]
I tested it and it works like a charm... I didn't know Django checked URLs in order and stopped at the first match, huh :thinking:

**Comment by danielgrijalva** [comment]
Fixed by #66
