### ISSUE TITLE
Show wishlist in profile stats

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#82]
Instead of showing the number of lists a user has, show how many games they have in their wishlist. 

> ![image](https://user-images.githubusercontent.com/11547406/60760714-4c753900-9ff7-11e9-9527-329e987af149.png)

This can be easily achieved, just take a look at how it is done with the games/backlog count.

**Comment by drsherlock** [comment]
Will pick it up.

**Comment by danielgrijalva** [comment]
Great, thanks!

**Comment by danielgrijalva** [comment]
Resolved by #83
