### ISSUE TITLE
Running 'python backend/manage.py migrate' breaks on windows

### ISSUE THREAD

**Issue by BenNF** [danielgrijalva/overworld#87]
**Describe the bug**
Running `python backend/manage.py migrate` breaks on windows with the following stacktrace. 

![image](https://user-images.githubusercontent.com/9667215/61059167-90d15200-a3c6-11e9-95f4-ec3850a3b866.png)

This is due to `os.environ["HOME"]` being used to get the path of the users home directory
the `HOME` key is platform specific and therefore breaks on windows.

I will submit a PR shortly to fix this.

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Comment by danielgrijalva** [comment]
Fixed by #88
