### ISSUE TITLE
Cannot install Semantic UI on windows with node version > 10.10.0

### ISSUE THREAD

**Issue by BenNF** [danielgrijalva/overworld#90]
Due to an ongoing bug in Semantic UI Semantic-Org/Semantic-UI#6641 It cannot be installed on windows with node version higher than 10.10.0.

Due to this issue running `npm ci` on windows breaks and does not complete the install.

A possible fix is adding `{ "engines" : { "node" : ">=6.0.0 <=10.10.0" } }` to package.json and package-lock.json

This will produce a warning if the user has a newer version of node installed that will not work on windows.

I'm happy to create a PR with this change.

**Comment by danielgrijalva** [comment]
Huh. Go ahead and create the PR :+1: thanks again!

**Comment by BenNF** [comment]
There doesn't seem to be an easy way to throw an error based on node version when doing a `npm install`  or `npm ci`. I'm just going to add a message to the setup documentation.
